[tox]
envlist = py311, py312
isolated_build = True
toxworkdir = /tmp/tox/{env:USER}/{toxinidir:name}

[testenv]
description = Run flake8 and pytest
extras = 
    dev
commands =
    # stop the build if there are Python syntax errors or undefined names
    flake8 src tests --count --select=E9,F63,F7,F82 --show-source --statistics
    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    flake8 src tests --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # Test with pytest
    pytest {posargs:tests}
